# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: User-defined Model
author: The Astropy Community
logo: logo.png

# Force re-execution of notebooks on each build
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: tutorial.tex

# Add a bibtex file to create citations
# bibtex_bibfiles:
#   - references.bib

repository:
  url: https://github.com/astropy/astropy-tutorials 
  # path_to_book: docs # Path to .ipynb, relative to the repository root (optional)
  branch: main/ # Branch of the repository to be used when creating links (optional) 

# Add buttons to notebook
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

launch_buttons:
  notebook_interface: "classic" # "jupyterlab"
  binderhub_url: "https://mybinder.org/v2/gh/astropy/astropy-tutorials/main?filepath=tutorials"
  thebe : true
