name: 'Execute and convert Jupyter notebook to HTML'

on:
  push:
    branches:
      - main
  schedule:
    # daily at 07:20 UTC
    - cron: "20 07 * * *"
  # allow manual triggering of workflow
  workflow_dispatch:

# allow only 1 instance of workflow at a time
concurrency:
  group: ${{ github.workflow }}

jobs:
  execute_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: astropy-learn/execute-convert@main
        with:
          python-version: "3.12"