name: 'Execute and convert Jupyter notebook to .html and .pdf'
on:
  push:
    branches:
      - main
  schedule:
    # daily at 07:20 UTC
    - cron: "20 07 * * *"
  # allow manual triggering of workflow
  workflow_dispatch:

# allow only 1 instance of workflow at a time
concurrency:
  group: ${{ github.workflow }}

jobs:
  execute_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out python scripts
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: add submodule
        run: git submodule add https://github.com/astropy-learn/astropy-tutorials
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build requirements
        shell: bash
        run: | 
          pip install pyyaml

      - name: populate-yaml-files
        id: py-yaml
        run: echo "TUTORIAL-SLUG=$(python astropy-tutorials/scripts/populate_yaml.py)" >> "$GITHUB_OUTPUT"

      - name: execute-convert-notebook
        uses: astropy-learn/execute-convert@main
        with: 
          # python-version: 3.12  
          tutorial-slug: ${{ steps.py-yaml.outputs.TUTORIAL-SLUG }}