name: 'Execute Jupyter notebook and convert the result to HTML'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  execute:
    runs-on: ubuntu-latest
    concurrency: post-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - uses: astropy-learn/execute-convert@main
        with:
          python-version: "3.12"