name: 'Execute and convert Jupyter notebook to HTML'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  execute_convert:
    runs-on: ubuntu-latest
    concurrency: post-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - uses: astropy-learn/execute-convert@main
        with:
          python-version: "3.12"