name: 'Execute and convert Jupyter notebook to .html and .pdf'
on:
  push:
    branches:
      - main
  schedule:
    # daily at 07:20 UTC
    - cron: "20 07 * * *"
  # allow manual triggering of workflow
  workflow_dispatch:

# allow only 1 instance of workflow at a time
concurrency:
  group: ${{ github.workflow }}

jobs:
  execute_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: populate-yaml-files
        id: py-yaml
        run: echo "TUTORIAL-SLUG=$(python populate_yaml.py) >> "$GITHUB_OUTPUT"

      - name: execute-convert-notebook
        uses: astropy-learn/execute-convert@main
        with: 
          # python-version: 3.12  
          tutorial-slug: ${{ steps.py-yaml.outputs.TUTORIAL-SLUG }}